-- ============================================
-- Create Smart Document tables IF NOT EXISTS
-- These tables were added to schema.prisma incrementally via db push
-- and are missing from the initial migration baseline.
-- Using IF NOT EXISTS to be idempotent across dev/staging/production.
-- ============================================

-- Smart Document enums are handled by Prisma's enum handling; MySQL uses VARCHAR CHECK constraints
-- Prisma 5 creates enums internally as (type + check) so we just create tables with raw types + indexes

CREATE TABLE IF NOT EXISTS `SmartDocumentStyleProfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profileName` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `isDefault` BOOLEAN NOT NULL DEFAULT false,
  `pageSize` VARCHAR(191) NOT NULL DEFAULT 'A4',
  `pageOrientation` VARCHAR(191) NOT NULL DEFAULT 'PORTRAIT',
  `pageWidthMm` DECIMAL(10,2) NULL,
  `pageHeightMm` DECIMAL(10,2) NULL,
  `marginTopMm` DECIMAL(10,2) NOT NULL DEFAULT 25.4,
  `marginBottomMm` DECIMAL(10,2) NOT NULL DEFAULT 25.4,
  `marginLeftMm` DECIMAL(10,2) NOT NULL DEFAULT 25.4,
  `marginRightMm` DECIMAL(10,2) NOT NULL DEFAULT 25.4,
  `bodyFontFamily` VARCHAR(191) NOT NULL DEFAULT 'Arial',
  `bodyFontSizePt` INT NOT NULL DEFAULT 11,
  `heading1FontSizePt` INT NOT NULL DEFAULT 16,
  `heading2FontSizePt` INT NOT NULL DEFAULT 14,
  `heading3FontSizePt` INT NOT NULL DEFAULT 12,
  `heading4FontSizePt` INT NOT NULL DEFAULT 11,
  `headingFontFamily` VARCHAR(191) NOT NULL DEFAULT 'Arial',
  `headingFontBold` BOOLEAN NOT NULL DEFAULT true,
  `tableFontFamily` VARCHAR(191) NOT NULL DEFAULT 'Arial',
  `tableFontSizePt` INT NOT NULL DEFAULT 10,
  `typographyJson` JSON NULL,
  `lineSpacing` DECIMAL(4,2) NOT NULL DEFAULT 1.15,
  `paragraphSpacingBeforePt` INT NOT NULL DEFAULT 0,
  `paragraphSpacingAfterPt` INT NOT NULL DEFAULT 6,
  `headerEnabled` BOOLEAN NOT NULL DEFAULT true,
  `headerHeightMm` DECIMAL(10,2) NULL,
  `headerLogoPath` VARCHAR(191) NULL,
  `headerUseProfessionalLayout` BOOLEAN NOT NULL DEFAULT true,
  `logoWidthMm` DECIMAL(10,2) NULL,
  `logoHeightMm` DECIMAL(10,2) NULL,
  `headerCompanyName` VARCHAR(191) NULL,
  `headerCompanyRegNo` VARCHAR(191) NULL,
  `headerCompanyNameUnderline` BOOLEAN NOT NULL DEFAULT true,
  `headerCompanyNameColor` VARCHAR(191) NULL DEFAULT '#1F2937',
  `headerCompanyAddressJson` JSON NULL,
  `headerCompanyPhone` VARCHAR(191) NULL,
  `headerCompanyEmail` VARCHAR(191) NULL,
  `headerCompanyEmailColor` VARCHAR(191) NULL DEFAULT '#0563C1',
  `headerBottomDividerEnabled` BOOLEAN NOT NULL DEFAULT true,
  `headerBottomDividerWidthPt` DECIMAL(4,2) NOT NULL DEFAULT 1.5,
  `headerBottomDividerColor` VARCHAR(191) NULL DEFAULT '#000000',
  `headerLeftText` TEXT NULL,
  `headerCenterText` TEXT NULL,
  `headerRightText` TEXT NULL,
  `headerBorderBottomStyle` VARCHAR(191) NULL DEFAULT 'single',
  `footerEnabled` BOOLEAN NOT NULL DEFAULT true,
  `footerHeightMm` DECIMAL(10,2) NULL,
  `footerUseProfessionalLayout` BOOLEAN NOT NULL DEFAULT true,
  `footerConfidentialText` VARCHAR(191) NULL,
  `footerClassificationMark` VARCHAR(191) NULL,
  `footerShowDocCodeAndRev` BOOLEAN NOT NULL DEFAULT true,
  `footerShowEffectiveDate` BOOLEAN NOT NULL DEFAULT true,
  `footerShowPreparedBy` BOOLEAN NOT NULL DEFAULT true,
  `footerShowApprovedBy` BOOLEAN NOT NULL DEFAULT false,
  `footerDisclaimerText` VARCHAR(191) NULL,
  `footerTopDividerEnabled` BOOLEAN NOT NULL DEFAULT true,
  `footerTopDividerWidthPt` DECIMAL(4,2) NOT NULL DEFAULT 0.75,
  `footerTopDividerColor` VARCHAR(191) NULL DEFAULT '#6B7280',
  `footerLeftText` TEXT NULL,
  `footerCenterText` TEXT NULL,
  `footerRightText` TEXT NULL,
  `showPageNumbers` BOOLEAN NOT NULL DEFAULT true,
  `pageNumberFormat` VARCHAR(191) NULL DEFAULT 'Page X of Y',
  `showDocumentInfo` BOOLEAN NOT NULL DEFAULT true,
  `footerBorderTopStyle` VARCHAR(191) NULL DEFAULT 'single',
  `tableBorderStyle` VARCHAR(191) NOT NULL DEFAULT 'single',
  `tableBorderWidthPt` DECIMAL(4,2) NOT NULL DEFAULT 0.5,
  `tableHeaderFillColor` VARCHAR(191) NULL DEFAULT '#F2F2F2',
  `tableHeaderFontBold` BOOLEAN NOT NULL DEFAULT true,
  `tableCellPaddingPt` INT NOT NULL DEFAULT 4,
  `tableAlignment` VARCHAR(191) NOT NULL DEFAULT 'left',
  `pageBreakBeforeHeadings` BOOLEAN NOT NULL DEFAULT true,
  `widowOrphanControl` BOOLEAN NOT NULL DEFAULT true,
  `firstPageNumber` INT NOT NULL DEFAULT 1,
  `restartOnEachSection` BOOLEAN NOT NULL DEFAULT false,
  `useHybridPageNumbering` BOOLEAN NOT NULL DEFAULT false,
  `frontMatterThreshold` INT NULL DEFAULT 4,
  `frontMatterFormat` VARCHAR(191) NULL DEFAULT 'lowerRoman',
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartDocumentStyleProfile_profileName_key` (`profileName`),
  INDEX `SmartDocumentStyleProfile_isActive_idx` (`isActive`),
  INDEX `SmartDocumentStyleProfile_isDefault_idx` (`isDefault`),
  INDEX `SmartDocumentStyleProfile_createdById_idx` (`createdById`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartTemplate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `templateName` VARCHAR(191) NOT NULL,
  `templateCode` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `documentTypeId` INT NOT NULL,
  `styleProfileId` INT NULL,
  `includeRevisionInDoc` BOOLEAN NOT NULL DEFAULT true,
  `includeFileCodeInDoc` BOOLEAN NOT NULL DEFAULT true,
  `includePreparedBy` BOOLEAN NOT NULL DEFAULT true,
  `includeDates` BOOLEAN NOT NULL DEFAULT true,
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartTemplate_templateCode_key` (`templateCode`),
  INDEX `SmartTemplate_documentTypeId_idx` (`documentTypeId`),
  INDEX `SmartTemplate_isActive_idx` (`isActive`),
  INDEX `SmartTemplate_templateCode_idx` (`templateCode`),
  INDEX `SmartTemplate_styleProfileId_idx` (`styleProfileId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartTemplateVersion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `smartTemplateId` INT NOT NULL,
  `versionNo` VARCHAR(191) NOT NULL,
  `versionLabel` VARCHAR(191) NULL,
  `templateFilePath` VARCHAR(191) NULL,
  `templateFileName` VARCHAR(191) NULL,
  `templateFileSize` INT NULL,
  `templateFileHash` VARCHAR(191) NULL,
  `templateUploadedAt` DATETIME(3) NULL,
  `placeholdersJson` JSON NULL,
  `formattingSnapshot` JSON NULL,
  `changeNotes` TEXT NULL,
  `isCurrent` BOOLEAN NOT NULL DEFAULT false,
  `isLocked` BOOLEAN NOT NULL DEFAULT false,
  `publishedById` INT NULL,
  `publishedAt` DATETIME(3) NULL,
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartTemplateVersion_smartTemplateId_versionNo_key` (`smartTemplateId`, `versionNo`),
  INDEX `SmartTemplateVersion_smartTemplateId_idx` (`smartTemplateId`),
  INDEX `SmartTemplateVersion_isCurrent_idx` (`isCurrent`),
  INDEX `SmartTemplateVersion_isLocked_idx` (`isLocked`),
  INDEX `SmartTemplateVersion_createdById_idx` (`createdById`),
  INDEX `SmartTemplateVersion_publishedById_idx` (`publishedById`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartTemplateSection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `smartTemplateVersionId` INT NOT NULL,
  `sectionKey` VARCHAR(191) NOT NULL,
  `sectionName` VARCHAR(191) NOT NULL,
  `sectionDescription` TEXT NULL,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `isRequired` BOOLEAN NOT NULL DEFAULT true,
  `isCollapsible` BOOLEAN NOT NULL DEFAULT true,
  `isSystemSection` BOOLEAN NOT NULL DEFAULT false,
  `sectionHelpText` TEXT NULL,
  `parentSectionId` INT NULL,
  `layoutConfig` JSON NULL,
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartTemplateSection_smartTemplateVersionId_sectionKey_key` (`smartTemplateVersionId`, `sectionKey`),
  INDEX `SmartTemplateSection_smartTemplateVersionId_idx` (`smartTemplateVersionId`),
  INDEX `SmartTemplateSection_parentSectionId_idx` (`parentSectionId`),
  INDEX `SmartTemplateSection_sortOrder_idx` (`sortOrder`),
  INDEX `SmartTemplateSection_createdById_idx` (`createdById`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartFormField` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `smartTemplateVersionId` INT NOT NULL,
  `smartTemplateSectionId` INT NULL,
  `fieldKey` VARCHAR(191) NOT NULL,
  `fieldLabel` VARCHAR(191) NOT NULL,
  `fieldHelpText` TEXT NULL,
  `placeholderHint` VARCHAR(191) NULL,
  `inputType` VARCHAR(191) NOT NULL DEFAULT 'TEXT',
  `optionsJson` JSON NULL,
  `validationRulesJson` JSON NULL,
  `defaultValueJson` JSON NULL,
  `tableSchemaJson` JSON NULL,
  `repeaterSchemaJson` JSON NULL,
  `imageConfigJson` JSON NULL,
  `attachmentConfigJson` JSON NULL,
  `systemFieldConfigJson` JSON NULL,
  `visibilityRulesJson` JSON NULL,
  `isMandatory` BOOLEAN NOT NULL DEFAULT false,
  `isEditableAuthor` BOOLEAN NOT NULL DEFAULT true,
  `isEditableReviewer` BOOLEAN NOT NULL DEFAULT false,
  `isVisibleInForm` BOOLEAN NOT NULL DEFAULT true,
  `isVisibleInPreview` BOOLEAN NOT NULL DEFAULT true,
  `isSearchable` BOOLEAN NOT NULL DEFAULT false,
  `isSupportingField` BOOLEAN NOT NULL DEFAULT false,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartFormField_smartTemplateVersionId_fieldKey_key` (`smartTemplateVersionId`, `fieldKey`),
  INDEX `SmartFormField_smartTemplateVersionId_idx` (`smartTemplateVersionId`),
  INDEX `SmartFormField_smartTemplateSectionId_idx` (`smartTemplateSectionId`),
  INDEX `SmartFormField_sortOrder_idx` (`sortOrder`),
  INDEX `SmartFormField_inputType_idx` (`inputType`),
  INDEX `SmartFormField_createdById_idx` (`createdById`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartFieldMapping` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `smartTemplateVersionId` INT NOT NULL,
  `smartFormFieldId` INT NOT NULL,
  `placeholderName` VARCHAR(191) NOT NULL,
  `placeholderType` VARCHAR(191) NOT NULL DEFAULT 'SIMPLE_VALUE',
  `outputFormatJson` JSON NULL,
  `targetSectionName` VARCHAR(191) NULL,
  `repeatParentTag` VARCHAR(191) NULL,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartFieldMapping_smartFormFieldId_key` (`smartFormFieldId`),
  UNIQUE INDEX `SmartFieldMapping_smartTemplateVersionId_placeholderName_key` (`smartTemplateVersionId`, `placeholderName`),
  INDEX `SmartFieldMapping_smartTemplateVersionId_idx` (`smartTemplateVersionId`),
  INDEX `SmartFieldMapping_smartFormFieldId_idx` (`smartFormFieldId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartDocumentContent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documentId` INT NOT NULL,
  `documentVersionId` INT NULL,
  `smartTemplateVersionId` INT NOT NULL,
  `fieldValuesJson` JSON NULL,
  `autoFieldSnapshotJson` JSON NULL,
  `contentChecksum` VARCHAR(191) NULL,
  `fieldAuditTrailJson` JSON NULL,
  `createdById` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SmartDocumentContent_documentVersionId_key` (`documentVersionId`),
  INDEX `SmartDocumentContent_documentId_idx` (`documentId`),
  INDEX `SmartDocumentContent_documentVersionId_idx` (`documentVersionId`),
  INDEX `SmartDocumentContent_smartTemplateVersionId_idx` (`smartTemplateVersionId`),
  INDEX `SmartDocumentContent_createdById_idx` (`createdById`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SmartDocumentFieldChange` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documentId` INT NOT NULL,
  `documentVersionId` INT NULL,
  `smartFormFieldKey` VARCHAR(191) NOT NULL,
  `changedById` INT NULL,
  `changedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `oldValueSnapshot` JSON NULL,
  `newValueSnapshot` JSON NULL,
  `changeReason` TEXT NULL,
  `workflowAction` VARCHAR(191) NULL,
  `sourceCommentId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `SmartDocumentFieldChange_documentId_idx` (`documentId`),
  INDEX `SmartDocumentFieldChange_documentVersionId_idx` (`documentVersionId`),
  INDEX `SmartDocumentFieldChange_smartFormFieldKey_idx` (`smartFormFieldKey`),
  INDEX `SmartDocumentFieldChange_changedById_idx` (`changedById`),
  INDEX `SmartDocumentFieldChange_changedAt_idx` (`changedAt`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
